import { RealEstate, Gaming, Technique } from "resources/Images"

const P2POrders = {
  REALESTATE: [
    {
      image: [RealEstate, Gaming, Technique],
      name: "1230 Boston Rd APT 29",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "1230 Boston Rd APT 230",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "1230 Boston Rd APT 29",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "1230 Boston Rd APT 230",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "1230 Boston Rd APT 29",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "1230 Boston Rd APT 230",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
  ],
  TECHNIQUE: [
    {
      image: [RealEstate, Gaming, Technique],
      name: "IoT",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "Robotics",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
  ],
  AUTOMOTIVE: [
    {
      image: [RealEstate, Gaming, Technique],
      name: "Ferarri",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "VolksWagen",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
  ],
  CRYPTO: [
    {
      image: [RealEstate, Gaming, Technique],
      name: "BNB",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "BNB",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
  ],
  P2PTRADING: [
    {
      image: [RealEstate, Gaming, Technique],
      name: "BTC Trading",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "BNB Trading",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
  ],
  GAMING: [
    {
      image: [RealEstate, Gaming, Technique],
      name: "The Witcher 3",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
    {
      image: [RealEstate, Gaming, Technique],
      name: "The Witcher 4",
      location: "Bronx, NY 10456",
      detail: ["3 Bedrooms", "1 Bathroom"],
      currency: "BNB",
      price: 250,
      trustable: false,
    },
  ],
}

export default P2POrders
